"""Process neutrino underground telemetry.

Load models and process event rates with snewpy, SNoGLoBES, and sspike.
"""


import tarfile
import pandas as pd
import numpy as np
import scipy.constants as cns

from snewpy import snowglobes

# Physics constants.
M_p = cns.physical_constants['proton mass energy equivalent in MeV'][0]
# Calculate number of targets in fiducial volume of radius R_f.
R_f = 600  # Radial volume cut [cm].
rho_p = 6.66e22  # KamLAND proton density [cm^-3].
N_p = 4 * np.pi * rho_p * R_f**3 / 3  # Number of protons in radius R_f.
N_e = N_p * 4.047  # Number of lectrons in radius R_f.

# Path to SNOeGLoBES ibd cross-section file
x_ibd = '/Users/joe/src/snowglobes/xscns/xs_ibd.dat'
x_e = '/Users/joe/src/snowglobes/xscns/xs_nue_e.dat'

# Directories.
# Location of snewpy models directory.
models_dir = '/Users/joe/src/snewpy/models/'
# SNOwGLoBES location.
snowglobes_path = "/Users/joe/src/gitjoe/snowglobes/"
# sspike snowball directory.
snowball_path = "/Users/joe/src/gitjoe/sspike/snowballs/"


def get_fluence(model, progenitor, transform, distance):
    """Save integrated fluence and return filepath."""
    # Simulation properties
    mass = progenitor['mass']
    metal = progenitor['metal']
    t_rev = progenitor['rev']
    # Supernovae model filename.
    model_file = f'nakazato-shen-z{metal}-t_rev{t_rev}ms-s{mass}.0.fits'
    model_path = f'{models_dir}/{model}/{model_file}'
    # Path for snowball.
    out_file = f"{model[:3]}-{mass}-{int(metal*1e3)}-{t_rev}-{distance}"

    # Generate fluence with snewpy and get path to output.
    snowball = snowglobes.generate_fluence(model_path, model, transform,
                                           distance, out_file)
    # Extract snewpy output in sspike snowball directory.
    with tarfile.open(snowball) as sb:
        sb.extractall(f"{snowball_path}{out_file}")

    return snowball, out_file


def snowglobes_events(snowball, out_file, detector):
    """Save events predicted using snewpy and SNOwGLoBES and
    return filepath.
    """
    # Simulate via snewpy and make a table of the results.
    snow = snowglobes.simulate(snowglobes_path, snowball,
                               detector_input=detector)

    # Save results
    smearing = ['unsmeared', 'smeared']
    snowflakes = []
    for smear in smearing:
        snow_path = f"{snowball_path}{out_file}/snow-{smear}.csv"
        events = snow[detector][out_file]['weighted', smear]
        events.to_csv(path_or_buf=snow_path, sep=' ')
        snowflakes.append(snow_path)

    return snowflakes


def sspike_events(snowball, out_file):
    """Process event rates using sspike functions."""
    # Load fluence (snowball) generated by snewpy.
    # Snowball format E(GeV)	NuE	NuMu	NuTau	aNuE	aNuMu	aNuTau
    names = ['E', 'nue', 'numu', 'nutau', 'nueb', 'numub', 'nutaub']
    # The values are separated by 3 spaces.  Skip 2 rows for header.
    sb = pd.read_csv(snowball, sep='   ', skiprows=2,
                     names=names, engine='python')

    sspikes = []
    # sspikes.append(e_scat(sb, out_file))
    sspikes.append(ibds(sb, out_file))

    return sspikes

def elastic_events(sb):
    """Save events predicted using sspike return filepath."""
    # Find differential cross-section as function of proton recoil energy.
    # dsig = dsig_dTp(sb)

    # Determine number of electron scattering events.
    pass


def e_scat(sb, out_file):
    """Given fluence dataframe, return electron events dataframe."""
    # Load cross-sections
    xscn = np.genfromtxt(x_e, skip_header=3).T
    # Energies [log(E GeV)] --> [GeV]
    x_E = 10**xscn[0]
    # Cross-sections [10^-38 cm^-2 GeV^-1] --> [cm^-2 GeV^-1]
    x_scale = 1e-38
    x_nue = xscn[1] * x_scale
    x_nueb = xscn[4] * x_scale
    x_nux = xscn[2] * x_scale

    # Number of events: fluence * xscn * N_electrons.
    # Multiply cross-sections from file (in GLoBES formatting) by energy.
    events = pd.DataFrame()
    # events['E'] = sb['E'][:]
    # Use the same energy grid as SNOwGLoBES
    events['E'] = np.linspace(7.49e-4, 9.975e-2, 200)

    # Electron flavor neutrinos.
    f_nue = np.interp(events['E'], sb['E'], sb['nue'])
    xs_nue = np.interp(events['E'], x_E, x_nue)
    events['nue_e'] = f_nue * xs_nue * events['E'] * N_e
    # Positron flavor neutrinos.
    f_nueb = np.interp(events['E'], sb['E'], sb['nueb'])
    xs_nueb = np.interp(events['E'], x_E, x_nueb)
    events['nue_e'] = f_nueb * xs_nueb * events['E'] * N_e
    # Extra factor of 4: nux = nu_mu + nu_mubar + nu_tau + nu_taubar.
    f_nux = np.interp(events['E'], sb['E'], sb['numu'])
    xs_nux = np.interp(events['E'], x_E, x_nux)
    events['nue_e'] = f_nux * xs_nux * events['E'] * N_e

    sspike_path = f"{snowball_path}{out_file}/sspike-e.csv"
    events.to_csv(path_or_buf=sspike_path, sep=' ')

    return sspike_path


def ibds(sb, out_file):
    """Given fluence dataframe, return electron events dataframe."""
    # Load cross-sections
    xscn = np.genfromtxt(x_ibd, skip_header=3).T
    # Energies [log(E GeV)] --> [GeV]
    x_E = 10**xscn[0]
    # Cross-sections [10^-38 cm^-2 GeV^-1] --> [cm^-2 GeV^-1]
    x_scale = 1e-38
    x_nueb = xscn[4] * x_scale

    # Number of events: fluence * xscn * bin-size * N_electrons.
    # Energy bins of 0.2 MeV in GeV.
    events = pd.DataFrame()
    # Use the same energy grid as SNOwGLoBES
    events['E'] = np.linspace(7.49e-4, 9.975e-2, 200)
    bin_size = events['E'][1] - events['E'][0]
    bin_scale = bin_size / 0.0002
    f_nueb = np.interp(events['E'], sb['E'], sb['nueb'])
    xs_nueb = np.interp(events['E'], x_E, x_nueb)
    events['ibd'] = f_nueb * xs_nueb * events['E'] * N_p * bin_scale

    sspike_path = f"{snowball_path}{out_file}/sspike-ibd.csv"
    events.to_csv(path_or_buf=sspike_path, sep=' ')

    return sspike_path


def dsig_dTp(sb):
    """Given fluence dataframe, return cross-section dataframe."""
    # Proton recoil energies possible for neutrino energy 100 MeV.
    T_p = np.arange(0.1, 17.6, 0.1)
    # N_bins = len(T_p)
    # Minimum required neutrino energy for proton recoil energy T.
    E_min = (T_p + np.sqrt(T_p * (T_p + 2 * M_p))) / 2

    # nue = np.zeros(N_bins)
    # nueb = np.zeros(N_bins)
    # nux = np.zeros(N_bins)

    return E_min
